[env]
PORT = "8080"
DATABASE_URL = "postgresql://postgres:muXCFeqmULzTxOyqPQNqvACGLdAcmfks@yamabiko.proxy.rlwy.net:27902/railway"
JWT_SECRET = "47EB1BCCDFB55!"

[[services]]
name = "backend"
type = "node"
root = "."
start = "npm start"
